id: PF00880F0
initial_creation_type: input
source_metadata:
  title: Tsongkhapa Lobzang Drakpa Series
  language: de
  description: 'Texts by and about the great master Tsongkhapa Lobzang Drakpa (tsong
    kha pa blo bzang grags pa) (1357–1419), founder of the Gelug school:'
  volume:
    11dc8a220054499c93588c33307d024e:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Guru Yoga
    042d81c527ad4a6286c66d0204eb15b8:
      title: Short Guru Yoga of the Noble Lord, All-Knowing Tsongkhapa
      parent: Guru Yoga
    fe8e995e76f4491aa802f60919bc2fde:
      title: Three Principal Aspects of the Path
      parent: Mind Training
    86e7e54568714574a8380e0047737669:
      title: Praise to Mañjughoṣa
      parent: Praise
    bb27d96380a24eb68252c2335329b98f:
      title: 'The Flower of Faith: Praise to the Great Lord Guru Tsongkhapa'
      parent: Praise
    38d97966be3d477b81ba63cb99d93b71:
      title: Aspiration for the Stages of the Path
      parent: Prayers
    c3dd2be391fc4999b3fc7e927d08ed7e:
      title: Prayer to Rendawa Shönnu Lodrö
      parent: Prayers
    ff7ae01dcf154df8be6de6adabb68eb8:
      title: The Foundation of All Qualities
      parent: Prayers
created_at: '2022-03-01T01:55:51.973073'
last_modified_at: '2022-03-01T01:55:51.973076'
